export const profileData = {
  name: "Sophia Chen",
  title: "Software Engineer",
  location: "San Francisco, CA",
  bio: "Experienced software engineer specializing in web development and cloud technologies. Passionate about building scalable and efficient applications.",
  avatar: "/profile.png",
  skills: [
    "JavaScript",
    "React",
    "Node.js",
    "Python",
    "Django",
    "AWS",
    "Docker",
    "SQL",
    "HTML & CSS",
  ],
  projects: [
    {
      id: 1,
      title: "Project Alpha",
      description: "A web application for managing tasks and projects.",
      technologies: ["React", "Node.js"],
    },
    {
      id: 2,
      title: "Project Beta",
      description: "A mobile app for tracking fitness activities.",
      technologies: ["Swift", "Firebase"],
    },
    {
      id: 3,
      title: "Project Gamma",
      description: "A platform for online learning and courses.",
      technologies: ["Vue.js", "Django"],
    },
    {
      id: 4,
      title: "Project Delta",
      description: "A tool for data analysis and visualization.",
      technologies: ["Python", "D3.js"],
    },
    {
      id: 5,
      title: "Project Epsilon",
      description: "A service for automating workflows.",
      technologies: ["Go", "AWS"],
    },
    {
      id: 6,
      title: "Project Zeta",
      description: "A system for managing customer relationships.",
      technologies: ["Ruby on Rails", "PostgreSQL"],
    },
    {
      id: 7,
      title: "Project Eta",
      description: "An e-commerce platform with payment integration.",
      technologies: ["React", "Stripe", "MongoDB"],
    },
    {
      id: 8,
      title: "Project Theta",
      description: "A real-time chat application.",
      technologies: ["Socket.io", "Express", "React"],
    },
    {
      id: 9,
      title: "Project Iota",
      description: "A machine learning model for image recognition.",
      technologies: ["Python", "TensorFlow", "OpenCV"],
    },
  ],
};
